//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaRepacker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaRepacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8800000_attack_10 {
            get {
                object obj = ResourceManager.GetObject("_8800000_attack_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser or image viewer is too OLD to view this image. Please download a newer browser such as Firefox..
        /// </summary>
        public static string AnimCompatMessage {
            get {
                return ResourceManager.GetString("AnimCompatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at animation builder, frame {0}.
        /// </summary>
        public static string AnimError {
            get {
                return ResourceManager.GetString("AnimError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated Portable Network Graphics (*.png).
        /// </summary>
        public static string ApngFilter {
            get {
                return ResourceManager.GetString("ApngFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cog {
            get {
                object obj = ResourceManager.GetObject("cog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foothold.
        /// </summary>
        public static string EditFoothold {
            get {
                return ResourceManager.GetString("EditFoothold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        public static string EditPortal {
            get {
                return ResourceManager.GetString("EditPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob spawnpoint.
        /// </summary>
        public static string EditSP {
            get {
                return ResourceManager.GetString("EditSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMS (old).
        /// </summary>
        public static string EncTypeGMS {
            get {
                return ResourceManager.GetString("EncTypeGMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSEA/Taiwan (old).
        /// </summary>
        public static string EncTypeMSEA {
            get {
                return ResourceManager.GetString("EncTypeMSEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMS/GMS/MapleSEA/メイプルストーリー/메이플스토리.
        /// </summary>
        public static string EncTypeNone {
            get {
                return ResourceManager.GetString("EncTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid input.
        /// </summary>
        public static string EnterValidInput {
            get {
                return ResourceManager.GetString("EnterValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid input.
        /// </summary>
        public static string EnterValidInput1 {
            get {
                return ResourceManager.GetString("EnterValidInput1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is only available under the x86 version of HaRepacker, please get the alternative version..
        /// </summary>
        public static string ExecutingAssemblyError {
            get {
                return ResourceManager.GetString("ExecutingAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input was invalid.
        ///Please provide valid values before confirming..
        /// </summary>
        public static string FHMapperInvalidInput {
            get {
                return ResourceManager.GetString("FHMapperInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to force value.
        /// </summary>
        public static string FHSettingsForceValue {
            get {
                return ResourceManager.GetString("FHSettingsForceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} was invalid.
        ///Please make sure all values are valid before confirming..
        /// </summary>
        public static string FHSettingsInvalidMessage {
            get {
                return ResourceManager.GetString("FHSettingsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next value.
        /// </summary>
        public static string FHSettingsNextValue {
            get {
                return ResourceManager.GetString("FHSettingsNextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portal type value.
        /// </summary>
        public static string FHSettingsPortalValue {
            get {
                return ResourceManager.GetString("FHSettingsPortalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prev value.
        /// </summary>
        public static string FHSettingsPrevValue {
            get {
                return ResourceManager.GetString("FHSettingsPrevValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X value.
        /// </summary>
        public static string FHSettingsXValue {
            get {
                return ResourceManager.GetString("FHSettingsXValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y value.
        /// </summary>
        public static string FHSettingsYValue {
            get {
                return ResourceManager.GetString("FHSettingsYValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_add {
            get {
                object obj = ResourceManager.GetObject("folder_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_go {
            get {
                object obj = ResourceManager.GetObject("folder_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images (*.jpg;*.bmp;*.png;*.gif;*.tiff).
        /// </summary>
        public static string ImagesFilter {
            get {
                return ResourceManager.GetString("ImagesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_default {
            get {
                object obj = ResourceManager.GetObject("img_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the WZ encryption used:.
        /// </summary>
        public static string InteractionWzMapleVersionInfo {
            get {
                return ResourceManager.GetString("InteractionWzMapleVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WZ Encryption.
        /// </summary>
        public static string InteractionWzMapleVersionTitle {
            get {
                return ResourceManager.GetString("InteractionWzMapleVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ladyboss_test_attack2_0 {
            get {
                object obj = ResourceManager.GetObject("ladyboss_test_attack2_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lightning {
            get {
                object obj = ResourceManager.GetObject("lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add canvas.
        /// </summary>
        public static string MainAddCanvas {
            get {
                return ResourceManager.GetString("MainAddCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add convex.
        /// </summary>
        public static string MainAddConvex {
            get {
                return ResourceManager.GetString("MainAddConvex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add directory.
        /// </summary>
        public static string MainAddDir {
            get {
                return ResourceManager.GetString("MainAddDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add double.
        /// </summary>
        public static string MainAddDouble {
            get {
                return ResourceManager.GetString("MainAddDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add float.
        /// </summary>
        public static string MainAddFloat {
            get {
                return ResourceManager.GetString("MainAddFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        public static string MainAddImg {
            get {
                return ResourceManager.GetString("MainAddImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add int.
        /// </summary>
        public static string MainAddInt {
            get {
                return ResourceManager.GetString("MainAddInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Type: {0}.
        /// </summary>
        public static string MainAdditionalInfo_PortalType {
            get {
                return ResourceManager.GetString("MainAdditionalInfo_PortalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link.
        /// </summary>
        public static string MainAddLink {
            get {
                return ResourceManager.GetString("MainAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add null.
        /// </summary>
        public static string MainAddNull {
            get {
                return ResourceManager.GetString("MainAddNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add short.
        /// </summary>
        public static string MainAddShort {
            get {
                return ResourceManager.GetString("MainAddShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sound.
        /// </summary>
        public static string MainAddSound {
            get {
                return ResourceManager.GetString("MainAddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add string.
        /// </summary>
        public static string MainAddString {
            get {
                return ResourceManager.GetString("MainAddString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sub.
        /// </summary>
        public static string MainAddSub {
            get {
                return ResourceManager.GetString("MainAddSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tab.
        /// </summary>
        public static string MainAddTabTitle {
            get {
                return ResourceManager.GetString("MainAddTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add vector.
        /// </summary>
        public static string MainAddVec {
            get {
                return ResourceManager.GetString("MainAddVec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is not an animation..
        /// </summary>
        public static string MainAnimationFail {
            get {
                return ResourceManager.GetString("MainAnimationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert selected object into this type of wz node..
        /// </summary>
        public static string MainCannotInsertToNode {
            get {
                return ResourceManager.GetString("MainCannotInsertToNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to abort the current operation?.
        /// </summary>
        public static string MainConfirmAbort {
            get {
                return ResourceManager.GetString("MainConfirmAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy WZ nodes to clipboard? (warning - can take a lot of time if many nodes are selected).
        /// </summary>
        public static string MainConfirmCopy {
            get {
                return ResourceManager.GetString("MainConfirmCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string MainConfirmExit {
            get {
                return ResourceManager.GetString("MainConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste WZ nodes from clipboard? (warning - can take a lot of time if many nodes are pasted).
        /// </summary>
        public static string MainConfirmPaste {
            get {
                return ResourceManager.GetString("MainConfirmPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this node?.
        /// </summary>
        public static string MainConfirmRemove {
            get {
                return ResourceManager.GetString("MainConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this node?.
        /// </summary>
        public static string MainConfirmRemoveNode {
            get {
                return ResourceManager.GetString("MainConfirmRemoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string MainConfirmRename {
            get {
                return ResourceManager.GetString("MainConfirmRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert &quot;{0}&quot; to the required type.
        /// </summary>
        public static string MainConversionError {
            get {
                return ResourceManager.GetString("MainConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t copy directories because they require too much memory.
        /// </summary>
        public static string MainCopyDirError {
            get {
                return ResourceManager.GetString("MainCopyDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open WZ file &quot;{0}&quot;.
        /// </summary>
        public static string MainCouldntOpenWZ {
            get {
                return ResourceManager.GetString("MainCouldntOpenWZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing {0}.img file. Are you sure you have selected the correct WZ encryption?.
        /// </summary>
        public static string MainErrorImportingWzImageFile {
            get {
                return ResourceManager.GetString("MainErrorImportingWzImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open/save to the specified file path. Please run as an Administrator instead..
        /// </summary>
        public static string MainFileOpenFail {
            get {
                return ResourceManager.GetString("MainFileOpenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help could not be shown because the help file ({0}) was not found.
        /// </summary>
        public static string MainHelpOpenFail {
            get {
                return ResourceManager.GetString("MainHelpOpenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load image.
        /// </summary>
        public static string MainImageLoadError {
            get {
                return ResourceManager.GetString("MainImageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; is invalid and will be skipped. Error: {1}.
        /// </summary>
        public static string MainInvalidFileError {
            get {
                return ResourceManager.GetString("MainInvalidFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file at {0} is a List.wz file and will be skipped..
        /// </summary>
        public static string MainListWzDetected {
            get {
                return ResourceManager.GetString("MainListWzDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A node with that name already exists. Please choose a different name.
        /// </summary>
        public static string MainNodeExists {
            get {
                return ResourceManager.GetString("MainNodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reload all files?.
        /// </summary>
        public static string MainReloadAll {
            get {
                return ResourceManager.GetString("MainReloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the WZ file to save.
        /// </summary>
        public static string MainSelectWzFolder {
            get {
                return ResourceManager.GetString("MainSelectWzFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find a parent WzFile to add this WzDirectoryProperty..
        /// </summary>
        public static string MainTreeAddDirError {
            get {
                return ResourceManager.GetString("MainTreeAddDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached the end of the tree.
        /// </summary>
        public static string MainTreeEnd {
            get {
                return ResourceManager.GetString("MainTreeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unload all files?.
        /// </summary>
        public static string MainUnloadAll {
            get {
                return ResourceManager.GetString("MainUnloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Click &quot;Yes&quot; to download the new version..
        /// </summary>
        public static string MainUpdateAvailable {
            get {
                return ResourceManager.GetString("MainUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version.
        /// </summary>
        public static string MainUpdateTitle {
            get {
                return ResourceManager.GetString("MainUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export directory not found. Please specify it under Tools -&gt; Options.
        /// </summary>
        public static string MainWzExportError {
            get {
                return ResourceManager.GetString("MainWzExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-1 Audio Layer 3 (*.mp3).
        /// </summary>
        public static string Mp3Filter {
            get {
                return ResourceManager.GetString("Mp3Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent must be above 0.
        /// </summary>
        public static string OptionsIndentError {
            get {
                return ResourceManager.GetString("OptionsIndentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap orangeMushroom_Jump {
            get {
                object obj = ResourceManager.GetObject("orangeMushroom_Jump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap orangeMushroom_Stand {
            get {
                object obj = ResourceManager.GetObject("orangeMushroom_Stand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_add {
            get {
                object obj = ResourceManager.GetObject("page_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_edit {
            get {
                object obj = ResourceManager.GetObject("page_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_go {
            get {
                object obj = ResourceManager.GetObject("page_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_white {
            get {
                object obj = ResourceManager.GetObject("page_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pause_ {
            get {
                object obj = ResourceManager.GetObject("Pause_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap play_ {
            get {
                object obj = ResourceManager.GetObject("play_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load settings file, make sure it is not in use. If it is not, delete it and try again..
        /// </summary>
        public static string ProgramLoadSettingsError {
            get {
                return ResourceManager.GetString("ProgramLoadSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red_x1 {
            get {
                object obj = ResourceManager.GetObject("red_x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node &quot;{0}&quot; already exists. Do you want it to be replaced?.
        /// </summary>
        public static string ReplaceConfirm {
            get {
                return ResourceManager.GetString("ReplaceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version must be above 0.
        /// </summary>
        public static string SaveVersionError {
            get {
                return ResourceManager.GetString("SaveVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select default XML folder.
        /// </summary>
        public static string SelectDefaultXmlFolder {
            get {
                return ResourceManager.GetString("SelectDefaultXmlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Type: {0}.
        /// </summary>
        public static string SelectionType {
            get {
                return ResourceManager.GetString("SelectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select MP3 File.
        /// </summary>
        public static string SelectMp3 {
            get {
                return ResourceManager.GetString("SelectMp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where to save the animation.
        /// </summary>
        public static string SelectOutApng {
            get {
                return ResourceManager.GetString("SelectOutApng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the output directory.
        /// </summary>
        public static string SelectOutDir {
            get {
                return ResourceManager.GetString("SelectOutDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where to save the file.
        /// </summary>
        public static string SelectOutWz {
            get {
                return ResourceManager.GetString("SelectOutWz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where to save the XML.
        /// </summary>
        public static string SelectOutXml {
            get {
                return ResourceManager.GetString("SelectOutXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the WZ File.
        /// </summary>
        public static string SelectWz {
            get {
                return ResourceManager.GetString("SelectWz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the IMG files.
        /// </summary>
        public static string SelectWzImg {
            get {
                return ResourceManager.GetString("SelectWzImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the XML files.
        /// </summary>
        public static string SelectXml {
            get {
                return ResourceManager.GetString("SelectXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Subpanel_Loading {
            get {
                return ResourceManager.GetString("Subpanel_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WZ File (*.wz).
        /// </summary>
        public static string WzFilter {
            get {
                return ResourceManager.GetString("WzFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WZ Image Files (*.img).
        /// </summary>
        public static string WzImgFilter {
            get {
                return ResourceManager.GetString("WzImgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eXtended Markup Language (*.xml).
        /// </summary>
        public static string XmlFilter {
            get {
                return ResourceManager.GetString("XmlFilter", resourceCulture);
            }
        }
    }
}
