//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaRepacker.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaRepacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animated Portable Network Graphics (*.png).
        /// </summary>
        internal static string ApngFilter {
            get {
                return ResourceManager.GetString("ApngFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cog {
            get {
                object obj = ResourceManager.GetObject("cog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foothold.
        /// </summary>
        internal static string EditFoothold {
            get {
                return ResourceManager.GetString("EditFoothold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portal.
        /// </summary>
        internal static string EditPortal {
            get {
                return ResourceManager.GetString("EditPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mob spawnpoint.
        /// </summary>
        internal static string EditSP {
            get {
                return ResourceManager.GetString("EditSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GMS (old).
        /// </summary>
        internal static string EncTypeGMS {
            get {
                return ResourceManager.GetString("EncTypeGMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MSEA/Taiwan (old).
        /// </summary>
        internal static string EncTypeMSEA {
            get {
                return ResourceManager.GetString("EncTypeMSEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BMS/GMS/MapleSEA/メイプルストーリー/메이플스토리.
        /// </summary>
        internal static string EncTypeNone {
            get {
                return ResourceManager.GetString("EncTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter valid input.
        /// </summary>
        internal static string EnterValidInput {
            get {
                return ResourceManager.GetString("EnterValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input was invalid.
        ///Please provide valid values before confirming..
        /// </summary>
        internal static string FHMapperInvalidInput {
            get {
                return ResourceManager.GetString("FHMapperInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a force value.
        /// </summary>
        internal static string FHSettingsForceValue {
            get {
                return ResourceManager.GetString("FHSettingsForceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} was invalid.
        ///Please make sure all values are valid before confirming..
        /// </summary>
        internal static string FHSettingsInvalidMessage {
            get {
                return ResourceManager.GetString("FHSettingsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a next value.
        /// </summary>
        internal static string FHSettingsNextValue {
            get {
                return ResourceManager.GetString("FHSettingsNextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a portal type value.
        /// </summary>
        internal static string FHSettingsPortalValue {
            get {
                return ResourceManager.GetString("FHSettingsPortalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a prev value.
        /// </summary>
        internal static string FHSettingsPrevValue {
            get {
                return ResourceManager.GetString("FHSettingsPrevValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a X value.
        /// </summary>
        internal static string FHSettingsXValue {
            get {
                return ResourceManager.GetString("FHSettingsXValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y value.
        /// </summary>
        internal static string FHSettingsYValue {
            get {
                return ResourceManager.GetString("FHSettingsYValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_add {
            get {
                object obj = ResourceManager.GetObject("folder_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_go {
            get {
                object obj = ResourceManager.GetObject("folder_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the WZ encryption used:.
        /// </summary>
        internal static string InteractionWzMapleVersionInfo {
            get {
                return ResourceManager.GetString("InteractionWzMapleVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WZ Encryption.
        /// </summary>
        internal static string InteractionWzMapleVersionTitle {
            get {
                return ResourceManager.GetString("InteractionWzMapleVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lightning {
            get {
                object obj = ResourceManager.GetObject("lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This item is not an animation..
        /// </summary>
        internal static string MainAnimationFail {
            get {
                return ResourceManager.GetString("MainAnimationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to abort the current operation?.
        /// </summary>
        internal static string MainConfirmAbort {
            get {
                return ResourceManager.GetString("MainConfirmAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to exit?.
        /// </summary>
        internal static string MainConfirmExit {
            get {
                return ResourceManager.GetString("MainConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to remove this node?.
        /// </summary>
        internal static string MainConfirmRemoveNode {
            get {
                return ResourceManager.GetString("MainConfirmRemoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not open WZ file &quot;{0}&quot;.
        /// </summary>
        internal static string MainCouldntOpenWZ {
            get {
                return ResourceManager.GetString("MainCouldntOpenWZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error importing {0}.img file. Are you sure you have selected the correct WZ encryption?.
        /// </summary>
        internal static string MainErrorImportingWzImageFile {
            get {
                return ResourceManager.GetString("MainErrorImportingWzImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help could not be shown because the help file ({0}) was not found.
        /// </summary>
        internal static string MainHelpOpenFail {
            get {
                return ResourceManager.GetString("MainHelpOpenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file &quot;{0}&quot; is invalid and will be skipped. Error: {1}.
        /// </summary>
        internal static string MainInvalidFileError {
            get {
                return ResourceManager.GetString("MainInvalidFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file at {0} is a List.wz file and will be skipped..
        /// </summary>
        internal static string MainListWzDetected {
            get {
                return ResourceManager.GetString("MainListWzDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to reload all files?.
        /// </summary>
        internal static string MainReloadAll {
            get {
                return ResourceManager.GetString("MainReloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select the WZ file to save.
        /// </summary>
        internal static string MainSelectWzFolder {
            get {
                return ResourceManager.GetString("MainSelectWzFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to unload all files?.
        /// </summary>
        internal static string MainUnloadAll {
            get {
                return ResourceManager.GetString("MainUnloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}
        ///
        ///Click &quot;Yes&quot; to download the new version..
        /// </summary>
        internal static string MainUpdateAvailable {
            get {
                return ResourceManager.GetString("MainUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Version.
        /// </summary>
        internal static string MainUpdateTitle {
            get {
                return ResourceManager.GetString("MainUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export directory not found. Please specify it under Tools -&gt; Options.
        /// </summary>
        internal static string MainWzExportError {
            get {
                return ResourceManager.GetString("MainWzExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indent must be above 0.
        /// </summary>
        internal static string OptionsIndentError {
            get {
                return ResourceManager.GetString("OptionsIndentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orangeMushroom_Jump {
            get {
                object obj = ResourceManager.GetObject("orangeMushroom_Jump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orangeMushroom_Stand {
            get {
                object obj = ResourceManager.GetObject("orangeMushroom_Stand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_add {
            get {
                object obj = ResourceManager.GetObject("page_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_edit {
            get {
                object obj = ResourceManager.GetObject("page_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_go {
            get {
                object obj = ResourceManager.GetObject("page_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white {
            get {
                object obj = ResourceManager.GetObject("page_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not load settings file, make sure it is not in use. If it is not, delete it and try again..
        /// </summary>
        internal static string ProgramLoadSettingsError {
            get {
                return ResourceManager.GetString("ProgramLoadSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version must be above 0.
        /// </summary>
        internal static string SaveVersionError {
            get {
                return ResourceManager.GetString("SaveVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select default XML folder.
        /// </summary>
        internal static string SelectDefaultXmlFolder {
            get {
                return ResourceManager.GetString("SelectDefaultXmlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select where to save the animation.
        /// </summary>
        internal static string SelectOutApng {
            get {
                return ResourceManager.GetString("SelectOutApng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the output directory.
        /// </summary>
        internal static string SelectOutDir {
            get {
                return ResourceManager.GetString("SelectOutDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select where to save the file.
        /// </summary>
        internal static string SelectOutWz {
            get {
                return ResourceManager.GetString("SelectOutWz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select where to save the XML.
        /// </summary>
        internal static string SelectOutXml {
            get {
                return ResourceManager.GetString("SelectOutXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the WZ File.
        /// </summary>
        internal static string SelectWz {
            get {
                return ResourceManager.GetString("SelectWz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the IMG files.
        /// </summary>
        internal static string SelectWzImg {
            get {
                return ResourceManager.GetString("SelectWzImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the XML files.
        /// </summary>
        internal static string SelectXml {
            get {
                return ResourceManager.GetString("SelectXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WZ File (*.wz).
        /// </summary>
        internal static string WzFilter {
            get {
                return ResourceManager.GetString("WzFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WZ Image Files (*.img).
        /// </summary>
        internal static string WzImgFilter {
            get {
                return ResourceManager.GetString("WzImgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eXtended Markup Language (*.xml).
        /// </summary>
        internal static string XmlFilter {
            get {
                return ResourceManager.GetString("XmlFilter", resourceCulture);
            }
        }
    }
}
