// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering
{
    public static partial class DirectionalBlurShaderKeys
    {
        public static readonly ValueParameterKey<float> Angle = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> BlurAmount = ParameterKeys.NewValue<float>(0.005f);
    }
}
