//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaSharedLibrary.Properties {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaSharedLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string WzEncTypeBMSDefault {
            get {
                return ResourceManager.GetString("WzEncTypeBMSDefault", resourceCulture);
            }
        }

        internal static string WzEncTypeCustomFormat {
            get {
                return ResourceManager.GetString("WzEncTypeCustomFormat", resourceCulture);
            }
        }

        internal static string WzEncTypeGenerate {
            get {
                return ResourceManager.GetString("WzEncTypeGenerate", resourceCulture);
            }
        }

        internal static string WzEncTypeGMS {
            get {
                return ResourceManager.GetString("WzEncTypeGMS", resourceCulture);
            }
        }

        internal static string WzEncTypeMSEA {
            get {
                return ResourceManager.GetString("WzEncTypeMSEA", resourceCulture);
            }
        }
    }
}
