//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaRepackerLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaRepackerLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser or image viewer is too OLD to view this image. Please download a newer browser such as Firefox..
        /// </summary>
        internal static string AnimCompatMessage {
            get {
                return ResourceManager.GetString("AnimCompatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at animation builder, frame {0}.
        /// </summary>
        internal static string AnimError {
            get {
                return ResourceManager.GetString("AnimError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid input.
        /// </summary>
        internal static string EnterValidInput {
            get {
                return ResourceManager.GetString("EnterValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images (*.jpg;*.bmp;*.png;*.gif;*.tiff).
        /// </summary>
        internal static string ImagesFilter {
            get {
                return ResourceManager.GetString("ImagesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_default {
            get {
                object obj = ResourceManager.GetObject("img_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add canvas.
        /// </summary>
        internal static string MainAddCanvas {
            get {
                return ResourceManager.GetString("MainAddCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add convex.
        /// </summary>
        internal static string MainAddConvex {
            get {
                return ResourceManager.GetString("MainAddConvex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add directory.
        /// </summary>
        internal static string MainAddDir {
            get {
                return ResourceManager.GetString("MainAddDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add double.
        /// </summary>
        internal static string MainAddDouble {
            get {
                return ResourceManager.GetString("MainAddDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add float.
        /// </summary>
        internal static string MainAddFloat {
            get {
                return ResourceManager.GetString("MainAddFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        internal static string MainAddImg {
            get {
                return ResourceManager.GetString("MainAddImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add int.
        /// </summary>
        internal static string MainAddInt {
            get {
                return ResourceManager.GetString("MainAddInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Type: {0}.
        /// </summary>
        internal static string MainAdditionalInfo_PortalType {
            get {
                return ResourceManager.GetString("MainAdditionalInfo_PortalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link.
        /// </summary>
        internal static string MainAddLink {
            get {
                return ResourceManager.GetString("MainAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add null.
        /// </summary>
        internal static string MainAddNull {
            get {
                return ResourceManager.GetString("MainAddNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add short.
        /// </summary>
        internal static string MainAddShort {
            get {
                return ResourceManager.GetString("MainAddShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sound.
        /// </summary>
        internal static string MainAddSound {
            get {
                return ResourceManager.GetString("MainAddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add string.
        /// </summary>
        internal static string MainAddString {
            get {
                return ResourceManager.GetString("MainAddString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sub.
        /// </summary>
        internal static string MainAddSub {
            get {
                return ResourceManager.GetString("MainAddSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add vector.
        /// </summary>
        internal static string MainAddVec {
            get {
                return ResourceManager.GetString("MainAddVec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert selected object into this type of wz node..
        /// </summary>
        internal static string MainCannotInsertToNode {
            get {
                return ResourceManager.GetString("MainCannotInsertToNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy WZ nodes to clipboard? (warning - can take a lot of time if many nodes are selected).
        /// </summary>
        internal static string MainConfirmCopy {
            get {
                return ResourceManager.GetString("MainConfirmCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste WZ nodes from clipboard? (warning - can take a lot of time if many nodes are pasted).
        /// </summary>
        internal static string MainConfirmPaste {
            get {
                return ResourceManager.GetString("MainConfirmPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this node?.
        /// </summary>
        internal static string MainConfirmRemove {
            get {
                return ResourceManager.GetString("MainConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string MainConfirmRename {
            get {
                return ResourceManager.GetString("MainConfirmRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert &quot;{0}&quot; to the required type.
        /// </summary>
        internal static string MainConversionError {
            get {
                return ResourceManager.GetString("MainConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t copy directories because they require too much memory.
        /// </summary>
        internal static string MainCopyDirError {
            get {
                return ResourceManager.GetString("MainCopyDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load image.
        /// </summary>
        internal static string MainImageLoadError {
            get {
                return ResourceManager.GetString("MainImageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A node with that name already exists. Please choose a different name.
        /// </summary>
        internal static string MainNodeExists {
            get {
                return ResourceManager.GetString("MainNodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find a parent WzFile to add this WzDirectoryProperty..
        /// </summary>
        internal static string MainTreeAddDirError {
            get {
                return ResourceManager.GetString("MainTreeAddDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached the end of the tree.
        /// </summary>
        internal static string MainTreeEnd {
            get {
                return ResourceManager.GetString("MainTreeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-1 Audio Layer 3 (*.mp3).
        /// </summary>
        internal static string Mp3Filter {
            get {
                return ResourceManager.GetString("Mp3Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_x1 {
            get {
                object obj = ResourceManager.GetObject("red_x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node &quot;{0}&quot; already exists. Do you want it to be replaced?.
        /// </summary>
        internal static string ReplaceConfirm {
            get {
                return ResourceManager.GetString("ReplaceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the image.
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Type: {0}.
        /// </summary>
        internal static string SelectionType {
            get {
                return ResourceManager.GetString("SelectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select MP3 File.
        /// </summary>
        internal static string SelectMp3 {
            get {
                return ResourceManager.GetString("SelectMp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
