//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaRepackerLib.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaRepackerLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your browser or image viewer is too OLD to view this image. Please download a newer browser such as Firefox..
        /// </summary>
        internal static string AnimCompatMessage {
            get {
                return ResourceManager.GetString("AnimCompatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error at animation builder, frame {0}.
        /// </summary>
        internal static string AnimError {
            get {
                return ResourceManager.GetString("AnimError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter valid input.
        /// </summary>
        internal static string EnterValidInput {
            get {
                return ResourceManager.GetString("EnterValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Images (*.jpg;*.bmp;*.png;*.gif;*.tiff).
        /// </summary>
        internal static string ImagesFilter {
            get {
                return ResourceManager.GetString("ImagesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_default {
            get {
                object obj = ResourceManager.GetObject("img_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add canvas.
        /// </summary>
        internal static string MainAddCanvas {
            get {
                return ResourceManager.GetString("MainAddCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add convex.
        /// </summary>
        internal static string MainAddConvex {
            get {
                return ResourceManager.GetString("MainAddConvex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add directory.
        /// </summary>
        internal static string MainAddDir {
            get {
                return ResourceManager.GetString("MainAddDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add double.
        /// </summary>
        internal static string MainAddDouble {
            get {
                return ResourceManager.GetString("MainAddDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add float.
        /// </summary>
        internal static string MainAddFloat {
            get {
                return ResourceManager.GetString("MainAddFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add image.
        /// </summary>
        internal static string MainAddImg {
            get {
                return ResourceManager.GetString("MainAddImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add int.
        /// </summary>
        internal static string MainAddInt {
            get {
                return ResourceManager.GetString("MainAddInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portal Type: {0}.
        /// </summary>
        internal static string MainAdditionalInfo_PortalType {
            get {
                return ResourceManager.GetString("MainAdditionalInfo_PortalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add link.
        /// </summary>
        internal static string MainAddLink {
            get {
                return ResourceManager.GetString("MainAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add null.
        /// </summary>
        internal static string MainAddNull {
            get {
                return ResourceManager.GetString("MainAddNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add short.
        /// </summary>
        internal static string MainAddShort {
            get {
                return ResourceManager.GetString("MainAddShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add sound.
        /// </summary>
        internal static string MainAddSound {
            get {
                return ResourceManager.GetString("MainAddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add string.
        /// </summary>
        internal static string MainAddString {
            get {
                return ResourceManager.GetString("MainAddString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add sub.
        /// </summary>
        internal static string MainAddSub {
            get {
                return ResourceManager.GetString("MainAddSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add vector.
        /// </summary>
        internal static string MainAddVec {
            get {
                return ResourceManager.GetString("MainAddVec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot insert selected object into this type of wz node..
        /// </summary>
        internal static string MainCannotInsertToNode {
            get {
                return ResourceManager.GetString("MainCannotInsertToNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy WZ nodes to clipboard? (warning - can take a lot of time if many nodes are selected).
        /// </summary>
        internal static string MainConfirmCopy {
            get {
                return ResourceManager.GetString("MainConfirmCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste WZ nodes from clipboard? (warning - can take a lot of time if many nodes are pasted).
        /// </summary>
        internal static string MainConfirmPaste {
            get {
                return ResourceManager.GetString("MainConfirmPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to remove this node?.
        /// </summary>
        internal static string MainConfirmRemove {
            get {
                return ResourceManager.GetString("MainConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not convert &quot;{0}&quot; to the required type.
        /// </summary>
        internal static string MainConversionError {
            get {
                return ResourceManager.GetString("MainConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t copy directories because they require too much memory.
        /// </summary>
        internal static string MainCopyDirError {
            get {
                return ResourceManager.GetString("MainCopyDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not load image.
        /// </summary>
        internal static string MainImageLoadError {
            get {
                return ResourceManager.GetString("MainImageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A node with that name already exists. Please choose a different name.
        /// </summary>
        internal static string MainNodeExists {
            get {
                return ResourceManager.GetString("MainNodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reached the end of the tree.
        /// </summary>
        internal static string MainTreeEnd {
            get {
                return ResourceManager.GetString("MainTreeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MPEG-1 Audio Layer 3 (*.mp3).
        /// </summary>
        internal static string Mp3Filter {
            get {
                return ResourceManager.GetString("Mp3Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_x1 {
            get {
                object obj = ResourceManager.GetObject("red_x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The node &quot;{0}&quot; already exists. Do you want it to be replaced?.
        /// </summary>
        internal static string ReplaceConfirm {
            get {
                return ResourceManager.GetString("ReplaceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the image.
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selection Type: {0}.
        /// </summary>
        internal static string SelectionType {
            get {
                return ResourceManager.GetString("SelectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select MP3 File.
        /// </summary>
        internal static string SelectMp3 {
            get {
                return ResourceManager.GetString("SelectMp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
